### ISSUE TITLE
新しいパッケージ名とコマンド名を決める

### ISSUE THREAD

**Issue by huequica** [huequica/pkfire#50]
# summary

- #47 このチケット内部で npx に動かすためにパッケージ名とコマンド名を統一しないといけなさそう、なので新しい名前を決める

**Comment by say-ya-sigma** [comment]
ignitionとinitをかけてignit

**Comment by say-ya-sigma** [comment]
ある〜

**Comment by huequica** [comment]
現状被ってない提案一覧
- pkfire
- pkthunder
- pker

**Comment by huequica** [comment]
- kictok
  - 草

**Comment by 54m** [comment]
nostar(node starter)

**Comment by 54m** [comment]
no-ki(node kicker / 納期)

**Comment by huequica** [comment]
- igot
  - ignition shot

**Comment by NISHI3** [comment]
* prcre
project create

**Comment by 54m** [comment]
- pkyan

**Comment by huequica** [comment]
@say-ya-sigma @54m @NISHI3 
MainMaintener 権限において新しい名称を **pkfire** とします

**Comment by NISHI3** [comment]
> @say-ya-sigma @54m @NISHI3 MainMaintener 権限において新しい名称を **pkfire** とします

一番パッとしててわかりやすいので賛成です！
